version: '3.4'

services:
  focus_incident_api:
    image: focus11.absa.co.za:5999/focus_incident_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8030
      - ASPNETCORE_HTTPS_PORT=8030
      - AUTHENTICATION_AUTHORITY=https://focus11.absa.co.za:8000
      - AUTHORIZATION_AUTHORITY=https://focus11.absa.co.za:8001
    ports: 
      - "8030:8030"
    build: 
      args:
        - profile=Production
        - http_proxy=http://22.150.52.72:3128
        - https_proxy=http://22.150.52.72:3128
    deploy:
      replicas: 1      
      placement: 
        constraints:
          - node.labels.role == api
    volumes:
      # mount the certificate bundle so that the backchannel authentication/authorization can validate the cert
      - ./etc/ssl/certs:/etc/ssl/certs:ro; 

  focus_incident_web:
    image: focus11.absa.co.za:5999/focus_incident_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8031
      - ASPNETCORE_HTTPS_PORT=8031
    ports: 
      - "8031:8031"
    build: 
      args:
        - profile=Production
        - http_proxy=http://22.150.52.72:3128
        - https_proxy=http://22.150.52.72:3128
    deploy:
      replicas: 1
      placement: 
        constraints:
          - node.labels.role == web

  focus_incident_job:
    image: focus11.absa.co.za:5999/focus_incident_job
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AUTHENTICATION_AUTHORITY=https://focus11.absa.co.za:8000
      - AUTHORIZATION_AUTHORITY=https://focus11.absa.co.za:8001
    build: 
      args:
        - profile=Production
        - http_proxy=http://22.150.52.72:3128
        - https_proxy=http://22.150.52.72:3128
    deploy:
      replicas: 1
      placement: 
        constraints:
          - node.labels.role == job
    volumes:
      # mount the certificate bundle so that the backchannel authentication/authorization can validate the cert
      - ./etc/ssl/certs:/etc/ssl/certs:ro;