version: '3.4'

services:
  focus_incident_api:
    image: retinadev.intra.absa.co.za:5999/focus_incident_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:8030
      - ASPNETCORE_HTTPS_PORT=8030
      - AUTHENTICATION_AUTHORITY=https://retinadev.intra.absa.co.za:8000
      - AUTHORIZATION_AUTHORITY=https://retinadev.intra.absa.co.za:8001
    ports:
      - "8030:8030"
    build: 
      args:
        - profile=Staging
        - http_proxy=http://22.150.52.72:3128
        - https_proxy=http://22.150.52.72:3128
    deploy:
      replicas: 1
    volumes:
      # mount the certificate bundle so that the backchannel authentication/authorization can validate the cert
      - ./etc/ssl/certs:/etc/ssl/certs:ro;

  focus_incident_web:
    image: retinadev.intra.absa.co.za:5999/focus_incident_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:8031
      - ASPNETCORE_HTTPS_PORT=8031
    ports: 
      - "8031:8031"
    build: 
      args:
        - profile=Staging
        - http_proxy=http://22.150.52.72:3128
        - https_proxy=http://22.150.52.72:3128
    deploy:
      replicas: 1

  focus_incident_job:
    image: retinadev.intra.absa.co.za:5999/focus_incident_job
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging     
      - AUTHENTICATION_AUTHORITY=https://retinadev.intra.absa.co.za:8000
      - AUTHORIZATION_AUTHORITY=https://retinadev.intra.absa.co.za:8001
    build: 
      args:
        - profile=Staging
        - http_proxy=http://22.150.52.72:3128
        - https_proxy=http://22.150.52.72:3128
    deploy:
      replicas: 1
    volumes:
      # mount the certificate bundle so that the backchannel authentication/authorization can validate the cert
      - ./etc/ssl/certs:/etc/ssl/certs:ro;
